# Generated by Django 6.0.5 on 2026-05-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(auto_created=True, unique=True)),
                ('employee_name', models.CharField(max_length=20)),
                ('employee_email', models.CharField(max_length=30)),
                ('employee_salary', models.FloatField()),
            ],
        ),
    ]
